// Generated by CoffeeScript 1.6.3
(function() {
  var ready;

  ready = function() {
    var getIssus, navClick;
    navClick = function() {
      $("ul.project-nav li").each(function() {
        $(this).removeClass("active");
      });
      $(this).parent().addClass("active");
      location.href = $(this).attr("href");
      getIssus($(this).attr("href"));
    };
    getIssus = function(href) {
      var issue_status, path, project_id;
      path = href.split("/");
      project_id = path[3];
      issue_status = path[5];
      return $.ajax({
        type: "get",
        url: "/issues/?project_id=" + project_id + "&status=" + issue_status,
        dataType: "json",
        success: function(data) {
          if (data.error !== "") {
            alert(data.error);
            return;
          }
          $(".btn-group-sm").html("<a href=\"/issues/?project_id=" + project_id + "&status=open\" class=\"btn btn-default btn-iss-status\" data-remote=\"true\">Open</a>" + "<a href=\"/issues/?project_id=" + project_id + "&status=closed\" class=\"btn btn-default btn-iss-status\" data-remote=\"true\">Closed</a>" + "<a href=\"/issues/?project_id=" + project_id + "&status=not_do_today\" class=\"btn btn-default btn-iss-status\" data-remote=\"true\">Don't do today</a>");
          return $("#issues").html(data.html);
        }
      });
    };
    $("ul.project-nav li a").on("click", navClick);
    location.href = $("ul.project-nav li a").first().attr("href");
    getIssus($("ul.project-nav li a").first().attr("href"));
  };

  $(document).ready(ready);

}).call(this);
