// Generated by CoffeeScript 1.4.0
(function() {
  var Issues;

  Issues = (function() {

    function Issues() {}

    Issues.prototype.get_issues = function(elm) {
      return $.ajax({
        type: 'get',
        url: elm.attr('href'),
        dataType: 'json',
        success: function(data) {
          if (data.error !== "") {
            alert(data.error);
          }
          return $('#issues').html(data.html);
        }
      });
    };

    Issues.prototype.get_assignee = function(elm) {
      var checked, project_id;
      project_id = $('#IssueProjectId').attr('value');
      checked = elm.prop('checked') ? '1' : '';
      return $.ajax({
        type: 'get',
        url: "/issues/" + project_id + "/assignee/",
        data: {
          github: checked
        },
        dataType: 'json',
        success: function(collection, dataType) {
          return $('#assignee-select-box').html(collection.html);
        },
        error: function(XMLHttpRequest, textStatus, errorThrown) {
          return alert("ERROR: " + textStatus);
        }
      });
    };

    return Issues;

  })();

  $(function() {
    var issues;
    issues = new Issues;
    $(document).on('click', '.btn-iss-status', function() {
      issues.get_issues($(this));
      return false;
    });
    return $(document).on('change', '#IssueGithub', function() {
      issues.get_assignee($(this));
      return false;
    });
  });

}).call(this);
