// Generated by CoffeeScript 1.6.3
(function() {
  var Issues;

  Issues = (function() {
    function Issues() {}

    Issues.prototype.get_issues = function(elm) {
      return $.ajax({
        type: 'get',
        url: elm.attr('href'),
        dataType: 'json',
        success: function(data) {
          if (data.error !== "") {
            alert(data.error);
          }
          return $('#issues').html(data.html);
        }
      });
    };

    return Issues;

  })();

  $(function() {
    var issues;
    issues = new Issues;
    return $(document).on('click', '.btn-iss-status', function() {
      issues.get_issues($(this));
      return false;
    });
  });

}).call(this);
