// Generated by CoffeeScript 1.6.3
(function() {
  var Members;

  Members = (function() {
    function Members() {}

    Members.prototype["delete"] = function(id) {
      return $.ajax({
        type: 'post',
        url: '/members/' + id + '/delete',
        dataType: 'json',
        data: {
          'method': "delete",
          'project_id': $('#project').data('projectid')
        },
        success: function(data) {
          if (data.status === 'error') {
            return alert(data.error);
          } else {
            return location.href = '/projects/' + $('#project').data('projectid') + '/members';
          }
        }
      });
    };

    return Members;

  })();

  $(function() {
    var members;
    members = new Members;
    return $('.btn-delete-member').click(function() {
      members["delete"]($(this).data('id'));
      return false;
    });
  });

}).call(this);
